version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro # 挂载主机时间设置
      - /etc/timezone:/etc/timezone:ro   # 挂载主机时区（可选）
    ports:
      - "39090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

