version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "14268:14268" # Jaeger HTTP Collector
      - "14250:14250" # Jaeger gRPC Collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true # 启用 OTLP
      - COLLECTOR_OTLP_HTTP_HOST_PORT=0.0.0.0:4318 # 配置 OTLP HTTP 接收端口
      - COLLECTOR_OTLP_GRPC_HOST_PORT=0.0.0.0:4317 # 配置 OTLP gRPC 接收端口