extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  opencensus:
    endpoint: 0.0.0.0:55678

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:7889']

  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_binary:
        endpoint: 0.0.0.0:6832
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268

  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
      endpoint: '192.168.68.189:24317'
      #endpoint: "http://jaeger:14268/api/traces"
      tls:
        insecure: true
  zipkin:
      endpoint: "http://192.168.68.189:9411/api/v2/spans"
  prometheus:
      endpoint: "0.0.0.0:7889"
#      endpoint: "192.168.68.189:9411"
#  logging:
#      loglevel: debug
#      insecure: true
#  jaeger:
#      endpoint: '0.0.0.0:14250'
#      insecure: true
service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,zipkin,otlp/jaeger]

    metrics:
      #receivers: [otlp, opencensus, prometheus]
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,prometheus]

#    logs:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [debug]

  extensions: [health_check, pprof, zpages]
