receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14317
      http:
        endpoint: 0.0.0.0:14318
processors:
  batch:


exporters:
  debug:
    verbosity: detailed
  zipkin:
      endpoint: "http://192.168.1.40:9411/api/v2/spans"
  otlp/jaeger:
      endpoint: '192.168.1.40:4317'
      tls:
        insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,zipkin,otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: []
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: []

